language: c

# trusty: Ubuntu 14.04
# https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

matrix:
  include:
    - os: linux
      sudo: false
      dist: bionic
      compiler: gcc
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc
    - os: linux
      sudo: false
      dist: bionic
      compiler: gcc-9
      env: CC="gcc-9" CXX="g++-9"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-9', 'g++-9']
    - os: linux
      sudo: false
      dist: bionic
      compiler: gcc-8
      env: CC="gcc-8" CXX="g++-8"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8', 'g++-8']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-7
      env: CC="gcc-7" CXX="g++-7"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-7', 'g++-7']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-6
      env: CC="gcc-6" CXX="g++-6"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-6', 'g++-6']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-5
      env: CC="gcc-5" CXX="g++-5"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'g++-5']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.9
      env: CC="gcc-4.9" CXX="g++-4.9"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9', 'g++-4.9']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.8
      env: CC="gcc-4.8" CXX="g++-4.8"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8', 'g++-4.8']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.7
      env: CC="gcc-4.7" CXX="g++-4.7"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.7', 'g++-4.7']
    - os: linux
      sudo: false
      dist: trusty
      env: CC="gcc-4.6" CXX="g++-4.6"
      compiler: gcc-4.6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.6', 'g++-4.6']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.4
      env: CC="gcc-4.4" CXX="g++-4.4"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.4', 'g++-4.4']
    - os: linux
      sudo: false
      dist: bionic
      compiler: clang
      env: CC="clang" CXX="clang++"
    - os: linux
      sudo: false
      dist: trusty
      compiler: clang
      env: CC="clang" CXX="clang++"
    - os: linux
      sudo: false
      dist: bionic
      compiler: clang-5.0
      env: CC="clang-5.0" CXX="clang++-5.0"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-bionic-5.0']
          packages: ['clang-5.0']
    - os: linux
      sudo: false
      dist: trusty
      compiler: clang-4.2
      env: CC="clang-4.2" CXX="clang++-4.2"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.2']
          packages: ['clang-4.2']
    - os: linux
      sudo: false
      dist: trusty
      compiler: clang-3.8
      env: CC="clang-3.8" CXX="clang++-3.8"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8']
          packages: ['clang-3.8']

    # Sanity check
    - os: osx
      compiler: clang

    - os: osx
      compiler: gcc

    # Older clang fails because clang-3.4 is not linked, but it might
    # work if we bothered to find the compiler.

script:
  - scripts/initbuild.sh make-concurrent
  - scripts/test.sh
