language: c

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.7']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.6']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.5']
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc-4.4
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.4']

    - os: linux
      sudo: false
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
          packages: ['clang']
    - os: linux
      sudo: false
      dist: trusty
      compiler: clang-3.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.8']
          packages: ['clang-3.8']
    - os: linux
      sudo: false
      dist: trusty
      compiler: clang-3.7
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.7']
          packages: ['clang-3.7']
    - os: linux
      sudo: false
      dist: trusty
      compiler: clang-3.6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.6']
          packages: ['clang-3.6']

    # Sanity check
    - os: osx
      compiler: clang

    - os: osx
      compiler: gcc

    # Older clang fails because clang-3.4 is not linked, but it might
    # work if we bothered to find the compiler.

script:
  - scripts/initbuild.sh make-concurrent
  - scripts/test.sh
