version: "win#{build}"

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - cmake --version
  - msbuild /version

shallow_clone: true

clone_folder: c:\projects\flatcc

environment:
  matrix:
    - arch: x86
      compiler: msvc2015
      backend: vs2015

    - arch: x64
      compiler: msvc2015
      backend: vs2015

configuration:
  - Debug
  - Release

install:
  - cmd set PATH=C:\Python35\scripts;%PATH%
  - cmd echo installing meson
  - cmd pip3 install meson

skip_tags: true

before_build:
  - echo Running cmake...
  - cd c:\projects\flatcc
  - mkdir build\MSVC
  - cd build\MSVC
  - if "%arch%"=="x86" cmake -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=%configuration% ..\..
  - if "%arch%"=="x64" cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%configuration% ..\..

build:
  parallel: true # enable MSBuild parallel builds
  project: c:\projects\flatcc\build\MSVC\FlatCC.sln

test_script:
  - ctest -C "%configuration%" -VV

